Capture DatabricksError when retrying API calls (#427)
## What changes are proposed in this pull request?

When requests are retried, there is currently no information available
to the caller to understand why. On retries no exception is logged and
on final retry, the cause is only available if an `IOException` were the
original source of failure rather. `DatabricksError` feels like a more
useful error to surface as this will capture the error from the server
which would have evaluated into a retriable error.

Currently the stacktrace appears as follows, which doesn't provide much
information:
```
com.databricks.sdk.core.DatabricksException: Request GET /api/2.1/unity-catalog/tables?catalog_name=<REDACTED>&schema_name=<REDACTED> failed after 4 retries
\tat com.databricks.sdk.core.ApiClient.executeInner(ApiClient.java:282)
\tat com.databricks.sdk.core.ApiClient.getResponse(ApiClient.java:235)
\tat com.databricks.sdk.core.ApiClient.execute(ApiClient.java:227)
\tat com.databricks.sdk.core.ApiClient.GET(ApiClient.java:148)
\tat com.databricks.sdk.service.catalog.TablesImpl.list(TablesImpl.java:47)
\tat com.databricks.sdk.support.Paginator.flipNextPage(Paginator.java:58)
\tat com.databricks.sdk.support.Paginator.<init>(Paginator.java:51)
\tat com.databricks.sdk.service.catalog.TablesAPI.list(TablesAPI.java:102)
\tat com.databricks.sdk.service.catalog.TablesAPI.list(TablesAPI.java:89)
```

## How is this tested?

Unit tests added.

Signed-off-by: Thomas Powell <tpowell@palantir.com>
Co-authored-by: Thomas Powell <tpowell@palantir.com>
Co-authored-by: Renaud Hartert <renaud.hartert@databricks.com>